// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: core.proto

package wujiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadJson   []byte                 `protobuf:"bytes,1,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *CallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TextStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	ThinkDelta    string                 `protobuf:"bytes,5,opt,name=think_delta,json=thinkDelta,proto3" json:"think_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextStreamChunk) Reset() {
	*x = TextStreamChunk{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextStreamChunk) ProtoMessage() {}

func (x *TextStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextStreamChunk.ProtoReflect.Descriptor instead.
func (*TextStreamChunk) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *TextStreamChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *TextStreamChunk) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *TextStreamChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TextStreamChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *TextStreamChunk) GetThinkDelta() string {
	if x != nil {
		return x.ThinkDelta
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type FileBlob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data  []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// When true, data is zstd-compressed.
	Zstd          bool `protobuf:"varint,3,opt,name=zstd,proto3" json:"zstd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileBlob) Reset() {
	*x = FileBlob{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileBlob) ProtoMessage() {}

func (x *FileBlob) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileBlob.ProtoReflect.Descriptor instead.
func (*FileBlob) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *FileBlob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileBlob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileBlob) GetZstd() bool {
	if x != nil {
		return x.Zstd
	}
	return false
}

type PutFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Files         []*FileBlob            `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFilesRequest) Reset() {
	*x = PutFilesRequest{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFilesRequest) ProtoMessage() {}

func (x *PutFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFilesRequest.ProtoReflect.Descriptor instead.
func (*PutFilesRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *PutFilesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PutFilesRequest) GetFiles() []*FileBlob {
	if x != nil {
		return x.Files
	}
	return nil
}

type PutFilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Paths []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	// Absolute server path to the session staging directory.
	StagingRoot   string `protobuf:"bytes,2,opt,name=staging_root,json=stagingRoot,proto3" json:"staging_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFilesResponse) Reset() {
	*x = PutFilesResponse{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFilesResponse) ProtoMessage() {}

func (x *PutFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFilesResponse.ProtoReflect.Descriptor instead.
func (*PutFilesResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *PutFilesResponse) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *PutFilesResponse) GetStagingRoot() string {
	if x != nil {
		return x.StagingRoot
	}
	return ""
}

type GetFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesRequest) Reset() {
	*x = GetFilesRequest{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesRequest) ProtoMessage() {}

func (x *GetFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesRequest.ProtoReflect.Descriptor instead.
func (*GetFilesRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *GetFilesRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type GetFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileBlob            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesResponse) Reset() {
	*x = GetFilesResponse{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesResponse) ProtoMessage() {}

func (x *GetFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesResponse.ProtoReflect.Descriptor instead.
func (*GetFilesResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *GetFilesResponse) GetFiles() []*FileBlob {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\awuji.v1\"H\n" +
	"\vCallRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\"G\n" +
	"\fCallResponse\x12!\n" +
	"\fpayload_json\x18\x01 \x01(\fR\vpayloadJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x95\x01\n" +
	"\x0fTextStreamChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12\x1f\n" +
	"\vthink_delta\x18\x05 \x01(\tR\n" +
	"thinkDelta\"\r\n" +
	"\vPingRequest\"8\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"F\n" +
	"\bFileBlob\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04zstd\x18\x03 \x01(\bR\x04zstd\"Y\n" +
	"\x0fPutFilesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x05files\x18\x02 \x03(\v2\x11.wuji.v1.FileBlobR\x05files\"K\n" +
	"\x10PutFilesResponse\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12!\n" +
	"\fstaging_root\x18\x02 \x01(\tR\vstagingRoot\"'\n" +
	"\x0fGetFilesRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\";\n" +
	"\x10GetFilesResponse\x12'\n" +
	"\x05files\x18\x01 \x03(\v2\x11.wuji.v1.FileBlobR\x05files2\xbe\x02\n" +
	"\bWujiCore\x123\n" +
	"\x04Call\x12\x14.wuji.v1.CallRequest\x1a\x15.wuji.v1.CallResponse\x12F\n" +
	"\x12GenerateTextStream\x12\x14.wuji.v1.CallRequest\x1a\x18.wuji.v1.TextStreamChunk0\x01\x123\n" +
	"\x04Ping\x12\x14.wuji.v1.PingRequest\x1a\x15.wuji.v1.PingResponse\x12?\n" +
	"\bPutFiles\x12\x18.wuji.v1.PutFilesRequest\x1a\x19.wuji.v1.PutFilesResponse\x12?\n" +
	"\bGetFiles\x12\x18.wuji.v1.GetFilesRequest\x1a\x19.wuji.v1.GetFilesResponseB8Z6github.com/coditary/wuji-core/api/proto/v1;wujiv1b\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_core_proto_goTypes = []any{
	(*CallRequest)(nil),      // 0: wuji.v1.CallRequest
	(*CallResponse)(nil),     // 1: wuji.v1.CallResponse
	(*TextStreamChunk)(nil),  // 2: wuji.v1.TextStreamChunk
	(*PingRequest)(nil),      // 3: wuji.v1.PingRequest
	(*PingResponse)(nil),     // 4: wuji.v1.PingResponse
	(*FileBlob)(nil),         // 5: wuji.v1.FileBlob
	(*PutFilesRequest)(nil),  // 6: wuji.v1.PutFilesRequest
	(*PutFilesResponse)(nil), // 7: wuji.v1.PutFilesResponse
	(*GetFilesRequest)(nil),  // 8: wuji.v1.GetFilesRequest
	(*GetFilesResponse)(nil), // 9: wuji.v1.GetFilesResponse
}
var file_core_proto_depIdxs = []int32{
	5, // 0: wuji.v1.PutFilesRequest.files:type_name -> wuji.v1.FileBlob
	5, // 1: wuji.v1.GetFilesResponse.files:type_name -> wuji.v1.FileBlob
	0, // 2: wuji.v1.WujiCore.Call:input_type -> wuji.v1.CallRequest
	0, // 3: wuji.v1.WujiCore.GenerateTextStream:input_type -> wuji.v1.CallRequest
	3, // 4: wuji.v1.WujiCore.Ping:input_type -> wuji.v1.PingRequest
	6, // 5: wuji.v1.WujiCore.PutFiles:input_type -> wuji.v1.PutFilesRequest
	8, // 6: wuji.v1.WujiCore.GetFiles:input_type -> wuji.v1.GetFilesRequest
	1, // 7: wuji.v1.WujiCore.Call:output_type -> wuji.v1.CallResponse
	2, // 8: wuji.v1.WujiCore.GenerateTextStream:output_type -> wuji.v1.TextStreamChunk
	4, // 9: wuji.v1.WujiCore.Ping:output_type -> wuji.v1.PingResponse
	7, // 10: wuji.v1.WujiCore.PutFiles:output_type -> wuji.v1.PutFilesResponse
	9, // 11: wuji.v1.WujiCore.GetFiles:output_type -> wuji.v1.GetFilesResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
