// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: core.proto

package wujiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WujiCore_Call_FullMethodName               = "/wuji.v1.WujiCore/Call"
	WujiCore_GenerateTextStream_FullMethodName = "/wuji.v1.WujiCore/GenerateTextStream"
	WujiCore_Ping_FullMethodName               = "/wuji.v1.WujiCore/Ping"
	WujiCore_PutFiles_FullMethodName           = "/wuji.v1.WujiCore/PutFiles"
	WujiCore_GetFiles_FullMethodName           = "/wuji.v1.WujiCore/GetFiles"
)

// WujiCoreClient is the client API for WujiCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WujiCore is the central daemon API. Workloads are dispatched via Call using JSON payloads.
type WujiCoreClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	GenerateTextStream(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TextStreamChunk], error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Stage local media on the daemon (remote CLI clients).
	PutFiles(ctx context.Context, in *PutFilesRequest, opts ...grpc.CallOption) (*PutFilesResponse, error)
	// Fetch generated media from the daemon back to the client.
	GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error)
}

type wujiCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewWujiCoreClient(cc grpc.ClientConnInterface) WujiCoreClient {
	return &wujiCoreClient{cc}
}

func (c *wujiCoreClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, WujiCore_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wujiCoreClient) GenerateTextStream(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TextStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WujiCore_ServiceDesc.Streams[0], WujiCore_GenerateTextStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CallRequest, TextStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WujiCore_GenerateTextStreamClient = grpc.ServerStreamingClient[TextStreamChunk]

func (c *wujiCoreClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, WujiCore_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wujiCoreClient) PutFiles(ctx context.Context, in *PutFilesRequest, opts ...grpc.CallOption) (*PutFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutFilesResponse)
	err := c.cc.Invoke(ctx, WujiCore_PutFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wujiCoreClient) GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFilesResponse)
	err := c.cc.Invoke(ctx, WujiCore_GetFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WujiCoreServer is the server API for WujiCore service.
// All implementations must embed UnimplementedWujiCoreServer
// for forward compatibility.
//
// WujiCore is the central daemon API. Workloads are dispatched via Call using JSON payloads.
type WujiCoreServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
	GenerateTextStream(*CallRequest, grpc.ServerStreamingServer[TextStreamChunk]) error
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Stage local media on the daemon (remote CLI clients).
	PutFiles(context.Context, *PutFilesRequest) (*PutFilesResponse, error)
	// Fetch generated media from the daemon back to the client.
	GetFiles(context.Context, *GetFilesRequest) (*GetFilesResponse, error)
	mustEmbedUnimplementedWujiCoreServer()
}

// UnimplementedWujiCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWujiCoreServer struct{}

func (UnimplementedWujiCoreServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedWujiCoreServer) GenerateTextStream(*CallRequest, grpc.ServerStreamingServer[TextStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method GenerateTextStream not implemented")
}
func (UnimplementedWujiCoreServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedWujiCoreServer) PutFiles(context.Context, *PutFilesRequest) (*PutFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutFiles not implemented")
}
func (UnimplementedWujiCoreServer) GetFiles(context.Context, *GetFilesRequest) (*GetFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFiles not implemented")
}
func (UnimplementedWujiCoreServer) mustEmbedUnimplementedWujiCoreServer() {}
func (UnimplementedWujiCoreServer) testEmbeddedByValue()                  {}

// UnsafeWujiCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WujiCoreServer will
// result in compilation errors.
type UnsafeWujiCoreServer interface {
	mustEmbedUnimplementedWujiCoreServer()
}

func RegisterWujiCoreServer(s grpc.ServiceRegistrar, srv WujiCoreServer) {
	// If the following call panics, it indicates UnimplementedWujiCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WujiCore_ServiceDesc, srv)
}

func _WujiCore_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WujiCoreServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WujiCore_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WujiCoreServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WujiCore_GenerateTextStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CallRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WujiCoreServer).GenerateTextStream(m, &grpc.GenericServerStream[CallRequest, TextStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WujiCore_GenerateTextStreamServer = grpc.ServerStreamingServer[TextStreamChunk]

func _WujiCore_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WujiCoreServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WujiCore_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WujiCoreServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WujiCore_PutFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WujiCoreServer).PutFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WujiCore_PutFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WujiCoreServer).PutFiles(ctx, req.(*PutFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WujiCore_GetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WujiCoreServer).GetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WujiCore_GetFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WujiCoreServer).GetFiles(ctx, req.(*GetFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WujiCore_ServiceDesc is the grpc.ServiceDesc for WujiCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WujiCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wuji.v1.WujiCore",
	HandlerType: (*WujiCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _WujiCore_Call_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _WujiCore_Ping_Handler,
		},
		{
			MethodName: "PutFiles",
			Handler:    _WujiCore_PutFiles_Handler,
		},
		{
			MethodName: "GetFiles",
			Handler:    _WujiCore_GetFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateTextStream",
			Handler:       _WujiCore_GenerateTextStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}
