// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: driver.proto

package wujiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DriverRegistry_Register_FullMethodName   = "/wuji.v1.DriverRegistry/Register"
	DriverRegistry_Heartbeat_FullMethodName  = "/wuji.v1.DriverRegistry/Heartbeat"
	DriverRegistry_Unregister_FullMethodName = "/wuji.v1.DriverRegistry/Unregister"
)

// DriverRegistryClient is the client API for DriverRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverRegistryClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
}

type driverRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverRegistryClient(cc grpc.ClientConnInterface) DriverRegistryClient {
	return &driverRegistryClient{cc}
}

func (c *driverRegistryClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, DriverRegistry_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverRegistryClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, DriverRegistry_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverRegistryClient) Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, DriverRegistry_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverRegistryServer is the server API for DriverRegistry service.
// All implementations must embed UnimplementedDriverRegistryServer
// for forward compatibility.
type DriverRegistryServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
	mustEmbedUnimplementedDriverRegistryServer()
}

// UnimplementedDriverRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverRegistryServer struct{}

func (UnimplementedDriverRegistryServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDriverRegistryServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDriverRegistryServer) Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedDriverRegistryServer) mustEmbedUnimplementedDriverRegistryServer() {}
func (UnimplementedDriverRegistryServer) testEmbeddedByValue()                        {}

// UnsafeDriverRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverRegistryServer will
// result in compilation errors.
type UnsafeDriverRegistryServer interface {
	mustEmbedUnimplementedDriverRegistryServer()
}

func RegisterDriverRegistryServer(s grpc.ServiceRegistrar, srv DriverRegistryServer) {
	// If the following call panics, it indicates UnimplementedDriverRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverRegistry_ServiceDesc, srv)
}

func _DriverRegistry_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverRegistryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverRegistry_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverRegistryServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverRegistry_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverRegistryServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverRegistry_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverRegistryServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverRegistry_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverRegistryServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverRegistry_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverRegistryServer).Unregister(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverRegistry_ServiceDesc is the grpc.ServiceDesc for DriverRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wuji.v1.DriverRegistry",
	HandlerType: (*DriverRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _DriverRegistry_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _DriverRegistry_Heartbeat_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _DriverRegistry_Unregister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver.proto",
}

const (
	DriverService_GetInfo_FullMethodName              = "/wuji.v1.DriverService/GetInfo"
	DriverService_GenerateText_FullMethodName         = "/wuji.v1.DriverService/GenerateText"
	DriverService_GenerateTextStream_FullMethodName   = "/wuji.v1.DriverService/GenerateTextStream"
	DriverService_GenerateImage_FullMethodName        = "/wuji.v1.DriverService/GenerateImage"
	DriverService_ImageToImage_FullMethodName         = "/wuji.v1.DriverService/ImageToImage"
	DriverService_InpaintImage_FullMethodName         = "/wuji.v1.DriverService/InpaintImage"
	DriverService_UpscaleImage_FullMethodName         = "/wuji.v1.DriverService/UpscaleImage"
	DriverService_EditImage_FullMethodName            = "/wuji.v1.DriverService/EditImage"
	DriverService_ControlNetImage_FullMethodName      = "/wuji.v1.DriverService/ControlNetImage"
	DriverService_DepthToImage_FullMethodName         = "/wuji.v1.DriverService/DepthToImage"
	DriverService_ImageVariation_FullMethodName       = "/wuji.v1.DriverService/ImageVariation"
	DriverService_StyleTransferImage_FullMethodName   = "/wuji.v1.DriverService/StyleTransferImage"
	DriverService_SpriteImage_FullMethodName          = "/wuji.v1.DriverService/SpriteImage"
	DriverService_GenerateVideo_FullMethodName        = "/wuji.v1.DriverService/GenerateVideo"
	DriverService_ImageToVideo_FullMethodName         = "/wuji.v1.DriverService/ImageToVideo"
	DriverService_InterpolateVideo_FullMethodName     = "/wuji.v1.DriverService/InterpolateVideo"
	DriverService_UpscaleVideo_FullMethodName         = "/wuji.v1.DriverService/UpscaleVideo"
	DriverService_GenerateMusic_FullMethodName        = "/wuji.v1.DriverService/GenerateMusic"
	DriverService_MelodyToMusic_FullMethodName        = "/wuji.v1.DriverService/MelodyToMusic"
	DriverService_GenerateSFX_FullMethodName          = "/wuji.v1.DriverService/GenerateSFX"
	DriverService_GenerateAudioSpeech_FullMethodName  = "/wuji.v1.DriverService/GenerateAudioSpeech"
	DriverService_GenerateMesh_FullMethodName         = "/wuji.v1.DriverService/GenerateMesh"
	DriverService_Video2Audio_FullMethodName          = "/wuji.v1.DriverService/Video2Audio"
	DriverService_CreateVoice_FullMethodName          = "/wuji.v1.DriverService/CreateVoice"
	DriverService_ConvertVoice_FullMethodName         = "/wuji.v1.DriverService/ConvertVoice"
	DriverService_ListVoiceProfiles_FullMethodName    = "/wuji.v1.DriverService/ListVoiceProfiles"
	DriverService_TrainText_FullMethodName            = "/wuji.v1.DriverService/TrainText"
	DriverService_TrainImage_FullMethodName           = "/wuji.v1.DriverService/TrainImage"
	DriverService_TrainVideo_FullMethodName           = "/wuji.v1.DriverService/TrainVideo"
	DriverService_TrainAudio_FullMethodName           = "/wuji.v1.DriverService/TrainAudio"
	DriverService_TrainMesh_FullMethodName            = "/wuji.v1.DriverService/TrainMesh"
	DriverService_TrainVoice_FullMethodName           = "/wuji.v1.DriverService/TrainVoice"
	DriverService_ListDatasets_FullMethodName         = "/wuji.v1.DriverService/ListDatasets"
	DriverService_CreateDataset_FullMethodName        = "/wuji.v1.DriverService/CreateDataset"
	DriverService_DeleteDataset_FullMethodName        = "/wuji.v1.DriverService/DeleteDataset"
	DriverService_IngestDataset_FullMethodName        = "/wuji.v1.DriverService/IngestDataset"
	DriverService_CreateDatasetVersion_FullMethodName = "/wuji.v1.DriverService/CreateDatasetVersion"
	DriverService_ListDatasetVersions_FullMethodName  = "/wuji.v1.DriverService/ListDatasetVersions"
	DriverService_ProduceData_FullMethodName          = "/wuji.v1.DriverService/ProduceData"
	DriverService_RunRAG_FullMethodName               = "/wuji.v1.DriverService/RunRAG"
)

// DriverServiceClient is the client API for DriverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverServiceClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	GenerateText(ctx context.Context, in *GenerateTextRequest, opts ...grpc.CallOption) (*GenerateTextResponse, error)
	GenerateTextStream(ctx context.Context, in *GenerateTextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TextStreamChunk], error)
	GenerateImage(ctx context.Context, in *GenerateImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
	ImageToImage(ctx context.Context, in *ImageToImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
	InpaintImage(ctx context.Context, in *InpaintImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
	UpscaleImage(ctx context.Context, in *UpscaleImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
	EditImage(ctx context.Context, in *EditImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
	ControlNetImage(ctx context.Context, in *ControlNetImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
	DepthToImage(ctx context.Context, in *DepthToImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
	ImageVariation(ctx context.Context, in *ImageVariationRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
	StyleTransferImage(ctx context.Context, in *StyleTransferImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
	SpriteImage(ctx context.Context, in *SpriteImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error)
	GenerateVideo(ctx context.Context, in *GenerateVideoRequest, opts ...grpc.CallOption) (*GenerateVideoResponse, error)
	ImageToVideo(ctx context.Context, in *ImageToVideoRequest, opts ...grpc.CallOption) (*GenerateVideoResponse, error)
	InterpolateVideo(ctx context.Context, in *InterpolateVideoRequest, opts ...grpc.CallOption) (*GenerateVideoResponse, error)
	UpscaleVideo(ctx context.Context, in *UpscaleVideoRequest, opts ...grpc.CallOption) (*GenerateVideoResponse, error)
	GenerateMusic(ctx context.Context, in *GenerateMusicRequest, opts ...grpc.CallOption) (*GenerateAudioResponse, error)
	MelodyToMusic(ctx context.Context, in *MelodyToMusicRequest, opts ...grpc.CallOption) (*GenerateAudioResponse, error)
	GenerateSFX(ctx context.Context, in *GenerateSFXRequest, opts ...grpc.CallOption) (*GenerateAudioResponse, error)
	GenerateAudioSpeech(ctx context.Context, in *GenerateAudioSpeechRequest, opts ...grpc.CallOption) (*GenerateAudioResponse, error)
	GenerateMesh(ctx context.Context, in *GenerateMeshRequest, opts ...grpc.CallOption) (*GenerateMeshResponse, error)
	Video2Audio(ctx context.Context, in *Video2AudioRequest, opts ...grpc.CallOption) (*Video2AudioResponse, error)
	CreateVoice(ctx context.Context, in *CreateVoiceRequest, opts ...grpc.CallOption) (*CloneVoiceResponse, error)
	ConvertVoice(ctx context.Context, in *ConvertVoiceRequest, opts ...grpc.CallOption) (*CloneVoiceResponse, error)
	ListVoiceProfiles(ctx context.Context, in *ListVoiceProfilesRequest, opts ...grpc.CallOption) (*ListVoiceProfilesResponse, error)
	TrainText(ctx context.Context, in *TrainTextRequest, opts ...grpc.CallOption) (*TrainResponse, error)
	TrainImage(ctx context.Context, in *TrainImageRequest, opts ...grpc.CallOption) (*TrainResponse, error)
	TrainVideo(ctx context.Context, in *TrainVideoRequest, opts ...grpc.CallOption) (*TrainResponse, error)
	TrainAudio(ctx context.Context, in *TrainAudioRequest, opts ...grpc.CallOption) (*TrainResponse, error)
	TrainMesh(ctx context.Context, in *TrainMeshRequest, opts ...grpc.CallOption) (*TrainResponse, error)
	TrainVoice(ctx context.Context, in *TrainVoiceRequest, opts ...grpc.CallOption) (*TrainResponse, error)
	ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error)
	CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*DatasetMutationResponse, error)
	DeleteDataset(ctx context.Context, in *DeleteDatasetRequest, opts ...grpc.CallOption) (*DatasetMutationResponse, error)
	IngestDataset(ctx context.Context, in *IngestDatasetRequest, opts ...grpc.CallOption) (*IngestDatasetResponse, error)
	CreateDatasetVersion(ctx context.Context, in *CreateDatasetVersionRequest, opts ...grpc.CallOption) (*DatasetVersionResponse, error)
	ListDatasetVersions(ctx context.Context, in *ListDatasetVersionsRequest, opts ...grpc.CallOption) (*ListDatasetVersionsResponse, error)
	ProduceData(ctx context.Context, in *ProduceDataRequest, opts ...grpc.CallOption) (*ProduceDataResponse, error)
	RunRAG(ctx context.Context, in *RAGRequestMsg, opts ...grpc.CallOption) (*RAGResponseMsg, error)
}

type driverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverServiceClient(cc grpc.ClientConnInterface) DriverServiceClient {
	return &driverServiceClient{cc}
}

func (c *driverServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, DriverService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GenerateText(ctx context.Context, in *GenerateTextRequest, opts ...grpc.CallOption) (*GenerateTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTextResponse)
	err := c.cc.Invoke(ctx, DriverService_GenerateText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GenerateTextStream(ctx context.Context, in *GenerateTextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TextStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DriverService_ServiceDesc.Streams[0], DriverService_GenerateTextStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateTextRequest, TextStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DriverService_GenerateTextStreamClient = grpc.ServerStreamingClient[TextStreamChunk]

func (c *driverServiceClient) GenerateImage(ctx context.Context, in *GenerateImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, DriverService_GenerateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ImageToImage(ctx context.Context, in *ImageToImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, DriverService_ImageToImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) InpaintImage(ctx context.Context, in *InpaintImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, DriverService_InpaintImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpscaleImage(ctx context.Context, in *UpscaleImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, DriverService_UpscaleImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) EditImage(ctx context.Context, in *EditImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, DriverService_EditImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ControlNetImage(ctx context.Context, in *ControlNetImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, DriverService_ControlNetImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) DepthToImage(ctx context.Context, in *DepthToImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, DriverService_DepthToImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ImageVariation(ctx context.Context, in *ImageVariationRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, DriverService_ImageVariation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) StyleTransferImage(ctx context.Context, in *StyleTransferImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, DriverService_StyleTransferImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) SpriteImage(ctx context.Context, in *SpriteImageRequest, opts ...grpc.CallOption) (*GenerateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImageResponse)
	err := c.cc.Invoke(ctx, DriverService_SpriteImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GenerateVideo(ctx context.Context, in *GenerateVideoRequest, opts ...grpc.CallOption) (*GenerateVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateVideoResponse)
	err := c.cc.Invoke(ctx, DriverService_GenerateVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ImageToVideo(ctx context.Context, in *ImageToVideoRequest, opts ...grpc.CallOption) (*GenerateVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateVideoResponse)
	err := c.cc.Invoke(ctx, DriverService_ImageToVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) InterpolateVideo(ctx context.Context, in *InterpolateVideoRequest, opts ...grpc.CallOption) (*GenerateVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateVideoResponse)
	err := c.cc.Invoke(ctx, DriverService_InterpolateVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpscaleVideo(ctx context.Context, in *UpscaleVideoRequest, opts ...grpc.CallOption) (*GenerateVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateVideoResponse)
	err := c.cc.Invoke(ctx, DriverService_UpscaleVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GenerateMusic(ctx context.Context, in *GenerateMusicRequest, opts ...grpc.CallOption) (*GenerateAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAudioResponse)
	err := c.cc.Invoke(ctx, DriverService_GenerateMusic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) MelodyToMusic(ctx context.Context, in *MelodyToMusicRequest, opts ...grpc.CallOption) (*GenerateAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAudioResponse)
	err := c.cc.Invoke(ctx, DriverService_MelodyToMusic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GenerateSFX(ctx context.Context, in *GenerateSFXRequest, opts ...grpc.CallOption) (*GenerateAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAudioResponse)
	err := c.cc.Invoke(ctx, DriverService_GenerateSFX_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GenerateAudioSpeech(ctx context.Context, in *GenerateAudioSpeechRequest, opts ...grpc.CallOption) (*GenerateAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAudioResponse)
	err := c.cc.Invoke(ctx, DriverService_GenerateAudioSpeech_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GenerateMesh(ctx context.Context, in *GenerateMeshRequest, opts ...grpc.CallOption) (*GenerateMeshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateMeshResponse)
	err := c.cc.Invoke(ctx, DriverService_GenerateMesh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) Video2Audio(ctx context.Context, in *Video2AudioRequest, opts ...grpc.CallOption) (*Video2AudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Video2AudioResponse)
	err := c.cc.Invoke(ctx, DriverService_Video2Audio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) CreateVoice(ctx context.Context, in *CreateVoiceRequest, opts ...grpc.CallOption) (*CloneVoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneVoiceResponse)
	err := c.cc.Invoke(ctx, DriverService_CreateVoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ConvertVoice(ctx context.Context, in *ConvertVoiceRequest, opts ...grpc.CallOption) (*CloneVoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneVoiceResponse)
	err := c.cc.Invoke(ctx, DriverService_ConvertVoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ListVoiceProfiles(ctx context.Context, in *ListVoiceProfilesRequest, opts ...grpc.CallOption) (*ListVoiceProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVoiceProfilesResponse)
	err := c.cc.Invoke(ctx, DriverService_ListVoiceProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) TrainText(ctx context.Context, in *TrainTextRequest, opts ...grpc.CallOption) (*TrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainResponse)
	err := c.cc.Invoke(ctx, DriverService_TrainText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) TrainImage(ctx context.Context, in *TrainImageRequest, opts ...grpc.CallOption) (*TrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainResponse)
	err := c.cc.Invoke(ctx, DriverService_TrainImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) TrainVideo(ctx context.Context, in *TrainVideoRequest, opts ...grpc.CallOption) (*TrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainResponse)
	err := c.cc.Invoke(ctx, DriverService_TrainVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) TrainAudio(ctx context.Context, in *TrainAudioRequest, opts ...grpc.CallOption) (*TrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainResponse)
	err := c.cc.Invoke(ctx, DriverService_TrainAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) TrainMesh(ctx context.Context, in *TrainMeshRequest, opts ...grpc.CallOption) (*TrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainResponse)
	err := c.cc.Invoke(ctx, DriverService_TrainMesh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) TrainVoice(ctx context.Context, in *TrainVoiceRequest, opts ...grpc.CallOption) (*TrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainResponse)
	err := c.cc.Invoke(ctx, DriverService_TrainVoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatasetsResponse)
	err := c.cc.Invoke(ctx, DriverService_ListDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) CreateDataset(ctx context.Context, in *CreateDatasetRequest, opts ...grpc.CallOption) (*DatasetMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatasetMutationResponse)
	err := c.cc.Invoke(ctx, DriverService_CreateDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) DeleteDataset(ctx context.Context, in *DeleteDatasetRequest, opts ...grpc.CallOption) (*DatasetMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatasetMutationResponse)
	err := c.cc.Invoke(ctx, DriverService_DeleteDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) IngestDataset(ctx context.Context, in *IngestDatasetRequest, opts ...grpc.CallOption) (*IngestDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestDatasetResponse)
	err := c.cc.Invoke(ctx, DriverService_IngestDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) CreateDatasetVersion(ctx context.Context, in *CreateDatasetVersionRequest, opts ...grpc.CallOption) (*DatasetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatasetVersionResponse)
	err := c.cc.Invoke(ctx, DriverService_CreateDatasetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ListDatasetVersions(ctx context.Context, in *ListDatasetVersionsRequest, opts ...grpc.CallOption) (*ListDatasetVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatasetVersionsResponse)
	err := c.cc.Invoke(ctx, DriverService_ListDatasetVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ProduceData(ctx context.Context, in *ProduceDataRequest, opts ...grpc.CallOption) (*ProduceDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProduceDataResponse)
	err := c.cc.Invoke(ctx, DriverService_ProduceData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) RunRAG(ctx context.Context, in *RAGRequestMsg, opts ...grpc.CallOption) (*RAGResponseMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAGResponseMsg)
	err := c.cc.Invoke(ctx, DriverService_RunRAG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServiceServer is the server API for DriverService service.
// All implementations must embed UnimplementedDriverServiceServer
// for forward compatibility.
type DriverServiceServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	GenerateText(context.Context, *GenerateTextRequest) (*GenerateTextResponse, error)
	GenerateTextStream(*GenerateTextRequest, grpc.ServerStreamingServer[TextStreamChunk]) error
	GenerateImage(context.Context, *GenerateImageRequest) (*GenerateImageResponse, error)
	ImageToImage(context.Context, *ImageToImageRequest) (*GenerateImageResponse, error)
	InpaintImage(context.Context, *InpaintImageRequest) (*GenerateImageResponse, error)
	UpscaleImage(context.Context, *UpscaleImageRequest) (*GenerateImageResponse, error)
	EditImage(context.Context, *EditImageRequest) (*GenerateImageResponse, error)
	ControlNetImage(context.Context, *ControlNetImageRequest) (*GenerateImageResponse, error)
	DepthToImage(context.Context, *DepthToImageRequest) (*GenerateImageResponse, error)
	ImageVariation(context.Context, *ImageVariationRequest) (*GenerateImageResponse, error)
	StyleTransferImage(context.Context, *StyleTransferImageRequest) (*GenerateImageResponse, error)
	SpriteImage(context.Context, *SpriteImageRequest) (*GenerateImageResponse, error)
	GenerateVideo(context.Context, *GenerateVideoRequest) (*GenerateVideoResponse, error)
	ImageToVideo(context.Context, *ImageToVideoRequest) (*GenerateVideoResponse, error)
	InterpolateVideo(context.Context, *InterpolateVideoRequest) (*GenerateVideoResponse, error)
	UpscaleVideo(context.Context, *UpscaleVideoRequest) (*GenerateVideoResponse, error)
	GenerateMusic(context.Context, *GenerateMusicRequest) (*GenerateAudioResponse, error)
	MelodyToMusic(context.Context, *MelodyToMusicRequest) (*GenerateAudioResponse, error)
	GenerateSFX(context.Context, *GenerateSFXRequest) (*GenerateAudioResponse, error)
	GenerateAudioSpeech(context.Context, *GenerateAudioSpeechRequest) (*GenerateAudioResponse, error)
	GenerateMesh(context.Context, *GenerateMeshRequest) (*GenerateMeshResponse, error)
	Video2Audio(context.Context, *Video2AudioRequest) (*Video2AudioResponse, error)
	CreateVoice(context.Context, *CreateVoiceRequest) (*CloneVoiceResponse, error)
	ConvertVoice(context.Context, *ConvertVoiceRequest) (*CloneVoiceResponse, error)
	ListVoiceProfiles(context.Context, *ListVoiceProfilesRequest) (*ListVoiceProfilesResponse, error)
	TrainText(context.Context, *TrainTextRequest) (*TrainResponse, error)
	TrainImage(context.Context, *TrainImageRequest) (*TrainResponse, error)
	TrainVideo(context.Context, *TrainVideoRequest) (*TrainResponse, error)
	TrainAudio(context.Context, *TrainAudioRequest) (*TrainResponse, error)
	TrainMesh(context.Context, *TrainMeshRequest) (*TrainResponse, error)
	TrainVoice(context.Context, *TrainVoiceRequest) (*TrainResponse, error)
	ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error)
	CreateDataset(context.Context, *CreateDatasetRequest) (*DatasetMutationResponse, error)
	DeleteDataset(context.Context, *DeleteDatasetRequest) (*DatasetMutationResponse, error)
	IngestDataset(context.Context, *IngestDatasetRequest) (*IngestDatasetResponse, error)
	CreateDatasetVersion(context.Context, *CreateDatasetVersionRequest) (*DatasetVersionResponse, error)
	ListDatasetVersions(context.Context, *ListDatasetVersionsRequest) (*ListDatasetVersionsResponse, error)
	ProduceData(context.Context, *ProduceDataRequest) (*ProduceDataResponse, error)
	RunRAG(context.Context, *RAGRequestMsg) (*RAGResponseMsg, error)
	mustEmbedUnimplementedDriverServiceServer()
}

// UnimplementedDriverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServiceServer struct{}

func (UnimplementedDriverServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedDriverServiceServer) GenerateText(context.Context, *GenerateTextRequest) (*GenerateTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateText not implemented")
}
func (UnimplementedDriverServiceServer) GenerateTextStream(*GenerateTextRequest, grpc.ServerStreamingServer[TextStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method GenerateTextStream not implemented")
}
func (UnimplementedDriverServiceServer) GenerateImage(context.Context, *GenerateImageRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateImage not implemented")
}
func (UnimplementedDriverServiceServer) ImageToImage(context.Context, *ImageToImageRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImageToImage not implemented")
}
func (UnimplementedDriverServiceServer) InpaintImage(context.Context, *InpaintImageRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InpaintImage not implemented")
}
func (UnimplementedDriverServiceServer) UpscaleImage(context.Context, *UpscaleImageRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpscaleImage not implemented")
}
func (UnimplementedDriverServiceServer) EditImage(context.Context, *EditImageRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditImage not implemented")
}
func (UnimplementedDriverServiceServer) ControlNetImage(context.Context, *ControlNetImageRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ControlNetImage not implemented")
}
func (UnimplementedDriverServiceServer) DepthToImage(context.Context, *DepthToImageRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DepthToImage not implemented")
}
func (UnimplementedDriverServiceServer) ImageVariation(context.Context, *ImageVariationRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImageVariation not implemented")
}
func (UnimplementedDriverServiceServer) StyleTransferImage(context.Context, *StyleTransferImageRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StyleTransferImage not implemented")
}
func (UnimplementedDriverServiceServer) SpriteImage(context.Context, *SpriteImageRequest) (*GenerateImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpriteImage not implemented")
}
func (UnimplementedDriverServiceServer) GenerateVideo(context.Context, *GenerateVideoRequest) (*GenerateVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateVideo not implemented")
}
func (UnimplementedDriverServiceServer) ImageToVideo(context.Context, *ImageToVideoRequest) (*GenerateVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImageToVideo not implemented")
}
func (UnimplementedDriverServiceServer) InterpolateVideo(context.Context, *InterpolateVideoRequest) (*GenerateVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InterpolateVideo not implemented")
}
func (UnimplementedDriverServiceServer) UpscaleVideo(context.Context, *UpscaleVideoRequest) (*GenerateVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpscaleVideo not implemented")
}
func (UnimplementedDriverServiceServer) GenerateMusic(context.Context, *GenerateMusicRequest) (*GenerateAudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateMusic not implemented")
}
func (UnimplementedDriverServiceServer) MelodyToMusic(context.Context, *MelodyToMusicRequest) (*GenerateAudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MelodyToMusic not implemented")
}
func (UnimplementedDriverServiceServer) GenerateSFX(context.Context, *GenerateSFXRequest) (*GenerateAudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateSFX not implemented")
}
func (UnimplementedDriverServiceServer) GenerateAudioSpeech(context.Context, *GenerateAudioSpeechRequest) (*GenerateAudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateAudioSpeech not implemented")
}
func (UnimplementedDriverServiceServer) GenerateMesh(context.Context, *GenerateMeshRequest) (*GenerateMeshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateMesh not implemented")
}
func (UnimplementedDriverServiceServer) Video2Audio(context.Context, *Video2AudioRequest) (*Video2AudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Video2Audio not implemented")
}
func (UnimplementedDriverServiceServer) CreateVoice(context.Context, *CreateVoiceRequest) (*CloneVoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVoice not implemented")
}
func (UnimplementedDriverServiceServer) ConvertVoice(context.Context, *ConvertVoiceRequest) (*CloneVoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertVoice not implemented")
}
func (UnimplementedDriverServiceServer) ListVoiceProfiles(context.Context, *ListVoiceProfilesRequest) (*ListVoiceProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVoiceProfiles not implemented")
}
func (UnimplementedDriverServiceServer) TrainText(context.Context, *TrainTextRequest) (*TrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrainText not implemented")
}
func (UnimplementedDriverServiceServer) TrainImage(context.Context, *TrainImageRequest) (*TrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrainImage not implemented")
}
func (UnimplementedDriverServiceServer) TrainVideo(context.Context, *TrainVideoRequest) (*TrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrainVideo not implemented")
}
func (UnimplementedDriverServiceServer) TrainAudio(context.Context, *TrainAudioRequest) (*TrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrainAudio not implemented")
}
func (UnimplementedDriverServiceServer) TrainMesh(context.Context, *TrainMeshRequest) (*TrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrainMesh not implemented")
}
func (UnimplementedDriverServiceServer) TrainVoice(context.Context, *TrainVoiceRequest) (*TrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrainVoice not implemented")
}
func (UnimplementedDriverServiceServer) ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatasets not implemented")
}
func (UnimplementedDriverServiceServer) CreateDataset(context.Context, *CreateDatasetRequest) (*DatasetMutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDataset not implemented")
}
func (UnimplementedDriverServiceServer) DeleteDataset(context.Context, *DeleteDatasetRequest) (*DatasetMutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDataset not implemented")
}
func (UnimplementedDriverServiceServer) IngestDataset(context.Context, *IngestDatasetRequest) (*IngestDatasetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestDataset not implemented")
}
func (UnimplementedDriverServiceServer) CreateDatasetVersion(context.Context, *CreateDatasetVersionRequest) (*DatasetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDatasetVersion not implemented")
}
func (UnimplementedDriverServiceServer) ListDatasetVersions(context.Context, *ListDatasetVersionsRequest) (*ListDatasetVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatasetVersions not implemented")
}
func (UnimplementedDriverServiceServer) ProduceData(context.Context, *ProduceDataRequest) (*ProduceDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProduceData not implemented")
}
func (UnimplementedDriverServiceServer) RunRAG(context.Context, *RAGRequestMsg) (*RAGResponseMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method RunRAG not implemented")
}
func (UnimplementedDriverServiceServer) mustEmbedUnimplementedDriverServiceServer() {}
func (UnimplementedDriverServiceServer) testEmbeddedByValue()                       {}

// UnsafeDriverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServiceServer will
// result in compilation errors.
type UnsafeDriverServiceServer interface {
	mustEmbedUnimplementedDriverServiceServer()
}

func RegisterDriverServiceServer(s grpc.ServiceRegistrar, srv DriverServiceServer) {
	// If the following call panics, it indicates UnimplementedDriverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverService_ServiceDesc, srv)
}

func _DriverService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GenerateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GenerateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GenerateText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GenerateText(ctx, req.(*GenerateTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GenerateTextStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateTextRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriverServiceServer).GenerateTextStream(m, &grpc.GenericServerStream[GenerateTextRequest, TextStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DriverService_GenerateTextStreamServer = grpc.ServerStreamingServer[TextStreamChunk]

func _DriverService_GenerateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GenerateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GenerateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GenerateImage(ctx, req.(*GenerateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ImageToImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageToImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ImageToImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ImageToImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ImageToImage(ctx, req.(*ImageToImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_InpaintImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InpaintImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).InpaintImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_InpaintImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).InpaintImage(ctx, req.(*InpaintImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpscaleImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpscaleImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpscaleImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpscaleImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpscaleImage(ctx, req.(*UpscaleImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_EditImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).EditImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_EditImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).EditImage(ctx, req.(*EditImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ControlNetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlNetImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ControlNetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ControlNetImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ControlNetImage(ctx, req.(*ControlNetImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_DepthToImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepthToImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).DepthToImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_DepthToImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).DepthToImage(ctx, req.(*DepthToImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ImageVariation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageVariationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ImageVariation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ImageVariation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ImageVariation(ctx, req.(*ImageVariationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_StyleTransferImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StyleTransferImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).StyleTransferImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_StyleTransferImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).StyleTransferImage(ctx, req.(*StyleTransferImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_SpriteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpriteImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).SpriteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_SpriteImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).SpriteImage(ctx, req.(*SpriteImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GenerateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GenerateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GenerateVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GenerateVideo(ctx, req.(*GenerateVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ImageToVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageToVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ImageToVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ImageToVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ImageToVideo(ctx, req.(*ImageToVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_InterpolateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterpolateVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).InterpolateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_InterpolateVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).InterpolateVideo(ctx, req.(*InterpolateVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpscaleVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpscaleVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpscaleVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpscaleVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpscaleVideo(ctx, req.(*UpscaleVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GenerateMusic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateMusicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GenerateMusic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GenerateMusic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GenerateMusic(ctx, req.(*GenerateMusicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_MelodyToMusic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MelodyToMusicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).MelodyToMusic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_MelodyToMusic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).MelodyToMusic(ctx, req.(*MelodyToMusicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GenerateSFX_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSFXRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GenerateSFX(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GenerateSFX_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GenerateSFX(ctx, req.(*GenerateSFXRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GenerateAudioSpeech_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAudioSpeechRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GenerateAudioSpeech(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GenerateAudioSpeech_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GenerateAudioSpeech(ctx, req.(*GenerateAudioSpeechRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GenerateMesh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateMeshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GenerateMesh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GenerateMesh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GenerateMesh(ctx, req.(*GenerateMeshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_Video2Audio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Video2AudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).Video2Audio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_Video2Audio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).Video2Audio(ctx, req.(*Video2AudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_CreateVoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).CreateVoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_CreateVoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).CreateVoice(ctx, req.(*CreateVoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ConvertVoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertVoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ConvertVoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ConvertVoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ConvertVoice(ctx, req.(*ConvertVoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ListVoiceProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVoiceProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ListVoiceProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ListVoiceProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ListVoiceProfiles(ctx, req.(*ListVoiceProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_TrainText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).TrainText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_TrainText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).TrainText(ctx, req.(*TrainTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_TrainImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).TrainImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_TrainImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).TrainImage(ctx, req.(*TrainImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_TrainVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).TrainVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_TrainVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).TrainVideo(ctx, req.(*TrainVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_TrainAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).TrainAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_TrainAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).TrainAudio(ctx, req.(*TrainAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_TrainMesh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainMeshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).TrainMesh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_TrainMesh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).TrainMesh(ctx, req.(*TrainMeshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_TrainVoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainVoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).TrainVoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_TrainVoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).TrainVoice(ctx, req.(*TrainVoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ListDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ListDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ListDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ListDatasets(ctx, req.(*ListDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_CreateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).CreateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_CreateDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).CreateDataset(ctx, req.(*CreateDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_DeleteDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).DeleteDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_DeleteDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).DeleteDataset(ctx, req.(*DeleteDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_IngestDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).IngestDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_IngestDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).IngestDataset(ctx, req.(*IngestDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_CreateDatasetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatasetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).CreateDatasetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_CreateDatasetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).CreateDatasetVersion(ctx, req.(*CreateDatasetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ListDatasetVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatasetVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ListDatasetVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ListDatasetVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ListDatasetVersions(ctx, req.(*ListDatasetVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ProduceData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProduceDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ProduceData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ProduceData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ProduceData(ctx, req.(*ProduceDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_RunRAG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGRequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).RunRAG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_RunRAG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).RunRAG(ctx, req.(*RAGRequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverService_ServiceDesc is the grpc.ServiceDesc for DriverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wuji.v1.DriverService",
	HandlerType: (*DriverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _DriverService_GetInfo_Handler,
		},
		{
			MethodName: "GenerateText",
			Handler:    _DriverService_GenerateText_Handler,
		},
		{
			MethodName: "GenerateImage",
			Handler:    _DriverService_GenerateImage_Handler,
		},
		{
			MethodName: "ImageToImage",
			Handler:    _DriverService_ImageToImage_Handler,
		},
		{
			MethodName: "InpaintImage",
			Handler:    _DriverService_InpaintImage_Handler,
		},
		{
			MethodName: "UpscaleImage",
			Handler:    _DriverService_UpscaleImage_Handler,
		},
		{
			MethodName: "EditImage",
			Handler:    _DriverService_EditImage_Handler,
		},
		{
			MethodName: "ControlNetImage",
			Handler:    _DriverService_ControlNetImage_Handler,
		},
		{
			MethodName: "DepthToImage",
			Handler:    _DriverService_DepthToImage_Handler,
		},
		{
			MethodName: "ImageVariation",
			Handler:    _DriverService_ImageVariation_Handler,
		},
		{
			MethodName: "StyleTransferImage",
			Handler:    _DriverService_StyleTransferImage_Handler,
		},
		{
			MethodName: "SpriteImage",
			Handler:    _DriverService_SpriteImage_Handler,
		},
		{
			MethodName: "GenerateVideo",
			Handler:    _DriverService_GenerateVideo_Handler,
		},
		{
			MethodName: "ImageToVideo",
			Handler:    _DriverService_ImageToVideo_Handler,
		},
		{
			MethodName: "InterpolateVideo",
			Handler:    _DriverService_InterpolateVideo_Handler,
		},
		{
			MethodName: "UpscaleVideo",
			Handler:    _DriverService_UpscaleVideo_Handler,
		},
		{
			MethodName: "GenerateMusic",
			Handler:    _DriverService_GenerateMusic_Handler,
		},
		{
			MethodName: "MelodyToMusic",
			Handler:    _DriverService_MelodyToMusic_Handler,
		},
		{
			MethodName: "GenerateSFX",
			Handler:    _DriverService_GenerateSFX_Handler,
		},
		{
			MethodName: "GenerateAudioSpeech",
			Handler:    _DriverService_GenerateAudioSpeech_Handler,
		},
		{
			MethodName: "GenerateMesh",
			Handler:    _DriverService_GenerateMesh_Handler,
		},
		{
			MethodName: "Video2Audio",
			Handler:    _DriverService_Video2Audio_Handler,
		},
		{
			MethodName: "CreateVoice",
			Handler:    _DriverService_CreateVoice_Handler,
		},
		{
			MethodName: "ConvertVoice",
			Handler:    _DriverService_ConvertVoice_Handler,
		},
		{
			MethodName: "ListVoiceProfiles",
			Handler:    _DriverService_ListVoiceProfiles_Handler,
		},
		{
			MethodName: "TrainText",
			Handler:    _DriverService_TrainText_Handler,
		},
		{
			MethodName: "TrainImage",
			Handler:    _DriverService_TrainImage_Handler,
		},
		{
			MethodName: "TrainVideo",
			Handler:    _DriverService_TrainVideo_Handler,
		},
		{
			MethodName: "TrainAudio",
			Handler:    _DriverService_TrainAudio_Handler,
		},
		{
			MethodName: "TrainMesh",
			Handler:    _DriverService_TrainMesh_Handler,
		},
		{
			MethodName: "TrainVoice",
			Handler:    _DriverService_TrainVoice_Handler,
		},
		{
			MethodName: "ListDatasets",
			Handler:    _DriverService_ListDatasets_Handler,
		},
		{
			MethodName: "CreateDataset",
			Handler:    _DriverService_CreateDataset_Handler,
		},
		{
			MethodName: "DeleteDataset",
			Handler:    _DriverService_DeleteDataset_Handler,
		},
		{
			MethodName: "IngestDataset",
			Handler:    _DriverService_IngestDataset_Handler,
		},
		{
			MethodName: "CreateDatasetVersion",
			Handler:    _DriverService_CreateDatasetVersion_Handler,
		},
		{
			MethodName: "ListDatasetVersions",
			Handler:    _DriverService_ListDatasetVersions_Handler,
		},
		{
			MethodName: "ProduceData",
			Handler:    _DriverService_ProduceData_Handler,
		},
		{
			MethodName: "RunRAG",
			Handler:    _DriverService_RunRAG_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateTextStream",
			Handler:       _DriverService_GenerateTextStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "driver.proto",
}
